// AUTO-GENERATED: maps normalized exercise names to public exercise photos
// Source: yuhonas/free-exercise-db (public domain), served via jsDelivr CDN.

export const EXERCISE_IMAGE_BASE = "https://cdn.jsdelivr.net/gh/yuhonas/free-exercise-db@main/exercises/";

/** normalized name -> image path within the CDN base */
export const EXERCISE_IMAGE_PATHS: Record<string, string> = {
  "ab crunch machine": "Ab_Crunch_Machine/0.jpg",
  "adductor machine": "Adductor/0.jpg",
  "alternating bicep curl dumbbell": "Machine_Bicep_Curl/0.jpg",
  "arm circles": "Arm_Circles/0.jpg",
  "arnold press": "Arnold_Dumbbell_Press/0.jpg",
  "arnold press dumbbell": "Arnold_Dumbbell_Press/0.jpg",
  "assisted pull up": "Band_Assisted_Pull-Up/0.jpg",
  "assisted pull up machine": "Band_Assisted_Pull-Up/0.jpg",
  "back extension": "Hyperextensions_Back_Extensions/0.jpg",
  "band pull apart": "Band_Pull_Apart/0.jpg",
  "barbell bench press": "Decline_Barbell_Bench_Press/0.jpg",
  "barbell curl": "Barbell_Curl/0.jpg",
  "barbell row": "Upright_Barbell_Row/0.jpg",
  "barbell shrug": "Barbell_Shrug/0.jpg",
  "behind the back wrist curl": "Standing_Palms-Up_Barbell_Behind_The_Back_Wrist_Curl/0.jpg",
  "behind the neck press": "Push_Press_-_Behind_the_Neck/0.jpg",
  "bench dip": "Bench_Dips/0.jpg",
  "bench press barbell": "Machine_Bench_Press/0.jpg",
  "bench press dumbbell": "Machine_Bench_Press/0.jpg",
  "bench press smith machine": "Machine_Bench_Press/0.jpg",
  "bent over row barbell": "Bent_Over_Barbell_Row/0.jpg",
  "bicep curl band": "Machine_Bicep_Curl/0.jpg",
  "bicep curl barbell": "Machine_Bicep_Curl/0.jpg",
  "bicep curl cable": "Machine_Bicep_Curl/0.jpg",
  "bicep curl dumbbell": "Machine_Bicep_Curl/0.jpg",
  "bicep curl ez bar": "Machine_Bicep_Curl/0.jpg",
  "bicep curl machine": "Machine_Bicep_Curl/0.jpg",
  "bodyweight squat": "Bodyweight_Squat/0.jpg",
  "box jump": "Front_Box_Jump/0.jpg",
  "box squat": "Box_Squat/0.jpg",
  "box squat barbell": "Box_Squat/0.jpg",
  "bulgarian split squat": "Split_Squats/0.jpg",
  "bulgarian split squat dumbbell": "Split_Squats/0.jpg",
  "cable crossover": "Cable_Crossover/0.jpg",
  "cable crunch": "Cable_Crunch/0.jpg",
  "cable curl": "Cable_Wrist_Curl/0.jpg",
  "cable fly": "Incline_Cable_Flye/0.jpg",
  "cable front raise": "Front_Cable_Raise/0.jpg",
  "cable hammer curl rope": "Cable_Hammer_Curls_-_Rope_Attachment/0.jpg",
  "cable kickback": "One-Legged_Cable_Kickback/0.jpg",
  "cable lateral raise": "Cable_Seated_Lateral_Raise/0.jpg",
  "cable pull through": "Pull_Through/0.jpg",
  "cable rear delt fly": "Cable_Rear_Delt_Fly/0.jpg",
  "cable upright row": "Upright_Cable_Row/0.jpg",
  "calf press leg press machine": "Calf_Press/0.jpg",
  "calf raise": "Smith_Machine_Calf_Raise/0.jpg",
  "calf raise barbell": "Smith_Machine_Calf_Raise/0.jpg",
  "calf raise dumbbell": "Smith_Machine_Calf_Raise/0.jpg",
  "calf stretch": "Seated_Calf_Stretch/0.jpg",
  "cat cow stretch": "Cat_Stretch/0.jpg",
  "cat stretch": "Cat_Stretch/0.jpg",
  "chest dip": "Dips_-_Chest_Version/0.jpg",
  "chest press band": "Cable_Chest_Press/0.jpg",
  "chest press machine": "Cable_Chest_Press/0.jpg",
  "child s pose": "Childs_Pose/0.jpg",
  "chin up": "Chin-Up/0.jpg",
  "clean and jerk": "Clean_and_Jerk/0.jpg",
  "clean pull": "Clean_Pull/0.jpg",
  "close grip bench press": "Smith_Machine_Close-Grip_Bench_Press/0.jpg",
  "close grip bench press barbell": "Smith_Machine_Close-Grip_Bench_Press/0.jpg",
  "close grip lat pulldown": "Close-Grip_Front_Lat_Pulldown/0.jpg",
  "concentration curl": "Concentration_Curls/0.jpg",
  "concentration curl dumbbell": "Concentration_Curls/0.jpg",
  "crunch": "Crunches/0.jpg",
  "crunch exercise ball": "Crunches/0.jpg",
  "dead bug": "Dead_Bug/0.jpg",
  "deadlift": "Car_Deadlift/0.jpg",
  "deadlift barbell": "Barbell_Deadlift/0.jpg",
  "decline barbell bench press": "Decline_Barbell_Bench_Press/0.jpg",
  "decline bench press barbell": "Decline_Barbell_Bench_Press/0.jpg",
  "decline push up": "Decline_Push-Up/0.jpg",
  "decline sit up": "Decline_Push-Up/0.jpg",
  "diamond push up": "Decline_Push-Up/0.jpg",
  "diamond push up triceps": "Decline_Push-Up/0.jpg",
  "dips chest": "Dip_Machine/0.jpg",
  "dips triceps": "Dip_Machine/0.jpg",
  "donkey calf raise": "Donkey_Calf_Raises/0.jpg",
  "doorway chest stretch": "Dynamic_Chest_Stretch/0.jpg",
  "drag curl": "Drag_Curl/0.jpg",
  "dumbbell bench press": "Dumbbell_Bench_Press/0.jpg",
  "dumbbell curl": "Dumbbell_Bicep_Curl/0.jpg",
  "dumbbell flyes": "Dumbbell_Flyes/0.jpg",
  "dumbbell row": "Dumbbell_Incline_Row/0.jpg",
  "dumbbell shoulder press": "Dumbbell_Shoulder_Press/0.jpg",
  "dumbbell shrug": "Dumbbell_Shrug/0.jpg",
  "dumbbell step up": "Dumbbell_Step_Ups/0.jpg",
  "elliptical trainer": "Elliptical_Trainer/0.jpg",
  "external rotation band": "External_Rotation/0.jpg",
  "ez bar curl": "EZ-Bar_Curl/0.jpg",
  "face pull": "Face_Pull/0.jpg",
  "face pull cable": "Face_Pull/0.jpg",
  "farmer s carry": "Farmers_Walk/0.jpg",
  "farmer s carry dumbbell": "Farmers_Walk/0.jpg",
  "floor press": "Floor_Press/0.jpg",
  "floor press kettlebell": "Floor_Press/0.jpg",
  "front raise": "Front_Leg_Raises/0.jpg",
  "front raise dumbbell": "Front_Dumbbell_Raise/0.jpg",
  "front raise plate": "Front_Plate_Raise/0.jpg",
  "front squat": "Front_Barbell_Squat/0.jpg",
  "front squat barbell": "Front_Barbell_Squat/0.jpg",
  "glute bridge": "Barbell_Glute_Bridge/0.jpg",
  "glute bridge barbell": "Barbell_Glute_Bridge/0.jpg",
  "glute bridges": "Barbell_Glute_Bridge/0.jpg",
  "glute ham raise": "Glute_Ham_Raise/0.jpg",
  "glute kickback cable": "Glute_Kickback/0.jpg",
  "goblet squat": "Goblet_Squat/0.jpg",
  "goblet squat dumbbell": "Goblet_Squat/0.jpg",
  "goblet squat kettlebell": "Goblet_Squat/0.jpg",
  "good morning": "Good_Morning/0.jpg",
  "good morning barbell": "Good_Morning/0.jpg",
  "hack squat": "Hack_Squat/0.jpg",
  "hack squat machine": "Hack_Squat/0.jpg",
  "hammer curl": "Hammer_Curls/0.jpg",
  "hammer curl dumbbell": "Hammer_Curls/0.jpg",
  "handstand push up": "Handstand_Push-Ups/0.jpg",
  "hang clean": "Hang_Clean/0.jpg",
  "hang snatch": "Hang_Snatch/0.jpg",
  "hanging knee raise": "Hanging_Leg_Raise/0.jpg",
  "hanging leg raise": "Hanging_Leg_Raise/0.jpg",
  "hip adduction machine": "Cable_Hip_Adduction/0.jpg",
  "hip circles": "Hip_Circles_prone/0.jpg",
  "hip thrust": "Barbell_Hip_Thrust/0.jpg",
  "hip thrust barbell": "Barbell_Hip_Thrust/0.jpg",
  "hyperextension": "Reverse_Hyperextension/0.jpg",
  "incline barbell bench press": "Decline_Barbell_Bench_Press/0.jpg",
  "incline bench press barbell": "Smith_Machine_Incline_Bench_Press/0.jpg",
  "incline bench press dumbbell": "Smith_Machine_Incline_Bench_Press/0.jpg",
  "incline cable fly": "Incline_Cable_Flye/0.jpg",
  "incline chest fly dumbbell": "Incline_Dumbbell_Flyes/0.jpg",
  "incline curl dumbbell": "Incline_Dumbbell_Curl/0.jpg",
  "incline dumbbell curl": "Incline_Dumbbell_Curl/0.jpg",
  "incline dumbbell press": "Incline_Dumbbell_Press/0.jpg",
  "internal rotation band": "Internal_Rotation_with_Band/0.jpg",
  "inverted row": "Inverted_Row/0.jpg",
  "jm press": "JM_Press/0.jpg",
  "jm press barbell": "JM_Press/0.jpg",
  "jump squat": "Freehand_Jump_Squat/0.jpg",
  "kettlebell bent over row": "Smith_Machine_Bent_Over_Row/0.jpg",
  "kettlebell bicep curl": "Machine_Bicep_Curl/0.jpg",
  "kettlebell clean": "Kettlebell_Dead_Clean/0.jpg",
  "kettlebell clean and press": "Clean_and_Press/0.jpg",
  "kettlebell cossack squat": "Kettlebell_Pistol_Squat/0.jpg",
  "kettlebell floor press double": "One-Arm_Kettlebell_Floor_Press/0.jpg",
  "kettlebell good morning": "Good_Morning/0.jpg",
  "kettlebell high pull": "Kettlebell_Sumo_High_Pull/0.jpg",
  "kettlebell jerk": "Double_Kettlebell_Jerk/0.jpg",
  "kettlebell push press": "Double_Kettlebell_Push_Press/0.jpg",
  "kettlebell romanian deadlift": "Romanian_Deadlift/0.jpg",
  "kettlebell russian twist": "Russian_Twist/0.jpg",
  "kettlebell sit up": "Sit-Up/0.jpg",
  "kettlebell snatch": "Double_Kettlebell_Snatch/0.jpg",
  "kettlebell split squat": "Split_Squats/0.jpg",
  "kettlebell sumo deadlift": "Sumo_Deadlift/0.jpg",
  "kettlebell swing": "One-Arm_Kettlebell_Swings/0.jpg",
  "kettlebell thruster": "Kettlebell_Thruster/0.jpg",
  "kettlebell turkish get up": "Kettlebell_Turkish_Get-Up_Lunge_style/0.jpg",
  "kettlebell upright row": "Smith_Machine_Upright_Row/0.jpg",
  "kettlebell windmill": "Kettlebell_Windmill/0.jpg",
  "kettlebell z press": "Kettlebell_Arnold_Press/0.jpg",
  "knee to chest stretch": "Chin_To_Chest_Stretch/0.jpg",
  "landmine shoulder press": "Cable_Shoulder_Press/0.jpg",
  "lat pulldown": "One_Arm_Lat_Pulldown/0.jpg",
  "lat pulldown cable": "One_Arm_Lat_Pulldown/0.jpg",
  "lateral raise": "Side_Lateral_Raise/0.jpg",
  "lateral raise cable": "Side_Lateral_Raise/0.jpg",
  "lateral raise dumbbell": "Side_Lateral_Raise/0.jpg",
  "leaning cable lateral raise": "Cable_Seated_Lateral_Raise/0.jpg",
  "leg curl": "Ball_Leg_Curl/0.jpg",
  "leg extension": "Leg_Extensions/0.jpg",
  "leg extension machine": "Leg_Extensions/0.jpg",
  "leg press": "Leg_Press/0.jpg",
  "leg press machine": "Leg_Press/0.jpg",
  "low cable crossover": "Low_Cable_Crossover/0.jpg",
  "lunge barbell": "Barbell_Lunge/0.jpg",
  "lying leg curl": "Lying_Leg_Curls/0.jpg",
  "lying leg curl machine": "Lying_Leg_Curls/0.jpg",
  "lying leg raise": "Flat_Bench_Lying_Leg_Raise/0.jpg",
  "lying side leg raises": "Side_Leg_Raises/0.jpg",
  "machine chest press": "Cable_Chest_Press/0.jpg",
  "machine row": "Smith_Machine_Upright_Row/0.jpg",
  "machine shoulder press": "Machine_Shoulder_Military_Press/0.jpg",
  "monster walk band": "Monster_Walk/0.jpg",
  "neutral grip pull up": "Wide-Grip_Rear_Pull-Up/0.jpg",
  "one arm row dumbbell": "One-Arm_Dumbbell_Row/0.jpg",
  "overhead cable tricep extension": "Cable_Rope_Overhead_Triceps_Extension/0.jpg",
  "overhead press": "Smith_Machine_Overhead_Shoulder_Press/0.jpg",
  "overhead press barbell": "Smith_Machine_Overhead_Shoulder_Press/0.jpg",
  "overhead press kettlebell": "Smith_Machine_Overhead_Shoulder_Press/0.jpg",
  "overhead squat": "Overhead_Squat/0.jpg",
  "overhead tricep extension": "Sled_Overhead_Triceps_Extension/0.jpg",
  "overhead triceps extension cable": "Sled_Overhead_Triceps_Extension/0.jpg",
  "overhead triceps extension dumbbell": "Sled_Overhead_Triceps_Extension/0.jpg",
  "pallof press": "Pallof_Press/0.jpg",
  "pelvic tilt": "Standing_Pelvic_Tilt/0.jpg",
  "pistol squat": "Smith_Machine_Pistol_Squat/0.jpg",
  "plank": "Plank/0.jpg",
  "plate front raise": "Front_Plate_Raise/0.jpg",
  "plate pinch hold": "Plate_Pinch/0.jpg",
  "plyometric push up": "Plyo_Push-up/0.jpg",
  "power clean": "Power_Clean/0.jpg",
  "power snatch": "Power_Snatch/0.jpg",
  "preacher curl": "Preacher_Curl/0.jpg",
  "preacher curl ez bar": "Preacher_Curl/0.jpg",
  "pull up": "Scapular_Pull-Up/0.jpg",
  "pullover dumbbell": "Bent-Arm_Dumbbell_Pullover/0.jpg",
  "push press": "Push_Press/0.jpg",
  "push press barbell": "Push_Press/0.jpg",
  "push up": "Plyo_Push-up/0.jpg",
  "rack pull": "Rack_Pull_with_Bands/0.jpg",
  "rack pull barbell": "Rack_Pull_with_Bands/0.jpg",
  "rear delt fly": "Cable_Rear_Delt_Fly/0.jpg",
  "rear delt fly cable": "Cable_Rear_Delt_Fly/0.jpg",
  "rear delt fly dumbbell": "Cable_Rear_Delt_Fly/0.jpg",
  "renegade row": "Alternating_Renegade_Row/0.jpg",
  "reverse crunch": "Reverse_Crunch/0.jpg",
  "reverse curl": "Reverse_Cable_Curl/0.jpg",
  "reverse curl barbell": "Reverse_Barbell_Curl/0.jpg",
  "reverse fly machine": "Reverse_Flyes/0.jpg",
  "reverse grip lat pulldown": "Wide-Grip_Lat_Pulldown/0.jpg",
  "reverse hyperextension": "Reverse_Hyperextension/0.jpg",
  "reverse lunge": "Crossover_Reverse_Lunge/0.jpg",
  "reverse wrist curl": "Reverse_Plate_Curls/0.jpg",
  "reverse wrist curl barbell": "Reverse_Barbell_Curl/0.jpg",
  "romanian deadlift": "Romanian_Deadlift/0.jpg",
  "romanian deadlift barbell": "Romanian_Deadlift/0.jpg",
  "romanian deadlift dumbbell": "Romanian_Deadlift/0.jpg",
  "rope hammer curl cable": "Cable_Hammer_Curls_-_Rope_Attachment/0.jpg",
  "rope tricep pushdown": "Triceps_Pushdown_-_Rope_Attachment/0.jpg",
  "row smith machine": "Smith_Machine_Upright_Row/0.jpg",
  "rowing machine": "Rowing_Stationary/0.jpg",
  "running outdoor": "Running_Treadmill/0.jpg",
  "russian twist": "Russian_Twist/0.jpg",
  "russian twist weight plate": "Russian_Twist/0.jpg",
  "seated cable row": "Seated_Cable_Rows/0.jpg",
  "seated calf raise": "Seated_Calf_Raise/0.jpg",
  "seated calf raise machine": "Seated_Calf_Raise/0.jpg",
  "seated dumbbell shoulder press": "Dumbbell_Shoulder_Press/0.jpg",
  "seated hamstring stretch": "Seated_Floor_Hamstring_Stretch/0.jpg",
  "seated leg curl": "Seated_Leg_Curl/0.jpg",
  "seated leg curl machine": "Seated_Leg_Curl/0.jpg",
  "seated row machine": "Seated_Cable_Rows/0.jpg",
  "seated shoulder press dumbbell": "Seated_Cable_Shoulder_Press/0.jpg",
  "shoulder pass through": "Lunge_Pass_Through/0.jpg",
  "shoulder press band": "Cable_Shoulder_Press/0.jpg",
  "shoulder press machine": "Cable_Shoulder_Press/0.jpg",
  "shrug barbell": "Barbell_Shrug/0.jpg",
  "shrug dumbbell": "Dumbbell_Shrug/0.jpg",
  "shrugs": "Cable_Shrugs/0.jpg",
  "side lying leg raise": "Side_Leg_Raises/0.jpg",
  "side plank": "Push_Up_to_Side_Plank/0.jpg",
  "single arm dumbbell bench press": "One_Arm_Dumbbell_Bench_Press/0.jpg",
  "single arm kb row": "One-Arm_Kettlebell_Row/0.jpg",
  "single arm kettlebell row": "One-Arm_Kettlebell_Row/0.jpg",
  "single arm kettlebell swing": "One-Arm_Kettlebell_Swings/0.jpg",
  "single leg glute bridge": "Single_Leg_Glute_Bridge/0.jpg",
  "sissy squat": "Weighted_Sissy_Squat/0.jpg",
  "sit up": "Sit-Up/0.jpg",
  "skull crusher dumbbell": "Band_Skull_Crusher/0.jpg",
  "skull crusher ez bar": "Band_Skull_Crusher/0.jpg",
  "skullcrusher": "EZ-Bar_Skullcrusher/0.jpg",
  "sled push": "Sled_Push/0.jpg",
  "smith machine bench press": "Smith_Machine_Bench_Press/0.jpg",
  "smith machine squat": "Smith_Machine_Squat/0.jpg",
  "snatch": "Snatch/0.jpg",
  "snatch pull": "Snatch_Pull/0.jpg",
  "spider curl": "Spider_Curl/0.jpg",
  "spider curl dumbbell": "Spider_Curl/0.jpg",
  "squat barbell": "Barbell_Squat/0.jpg",
  "squat smith machine": "Smith_Machine_Squat/0.jpg",
  "squat to calf raise": "Smith_Machine_Calf_Raise/0.jpg",
  "standing calf raise": "Standing_Calf_Raises/0.jpg",
  "standing calf raise machine": "Standing_Calf_Raises/0.jpg",
  "standing hamstring stretch": "Standing_Hamstring_and_Calf_Stretch/0.jpg",
  "standing quad stretch": "Standing_Elevated_Quad_Stretch/0.jpg",
  "step up": "Barbell_Step_Ups/0.jpg",
  "step up dumbbell": "Dumbbell_Step_Ups/0.jpg",
  "step up low box": "Barbell_Step_Ups/0.jpg",
  "stiff leg deadlift barbell": "Stiff-Legged_Barbell_Deadlift/0.jpg",
  "straight arm pulldown": "Straight-Arm_Pulldown/0.jpg",
  "straight arm pulldown cable": "Straight-Arm_Pulldown/0.jpg",
  "straight leg raise": "Hanging_Leg_Raise/0.jpg",
  "sumo deadlift": "Sumo_Deadlift/0.jpg",
  "sumo deadlift barbell": "Sumo_Deadlift/0.jpg",
  "superman": "Superman/0.jpg",
  "svend press": "Svend_Press/0.jpg",
  "t bar row": "Lying_T-Bar_Row/0.jpg",
  "thruster": "Kettlebell_Thruster/0.jpg",
  "trap bar deadlift": "Trap_Bar_Deadlift/0.jpg",
  "tricep pushdown": "Triceps_Pushdown/0.jpg",
  "triceps dip": "Dips_-_Triceps_Version/0.jpg",
  "triceps extension machine": "Machine_Triceps_Extension/0.jpg",
  "triceps kickback dumbbell": "Tricep_Dumbbell_Kickback/0.jpg",
  "triceps pushdown band": "Triceps_Pushdown/0.jpg",
  "triceps pushdown cable bar": "Triceps_Pushdown/0.jpg",
  "triceps pushdown cable rope": "Triceps_Pushdown/0.jpg",
  "turkish get up": "Kettlebell_Turkish_Get-Up_Lunge_style/0.jpg",
  "upper trap stretch": "Upper_Back_Stretch/0.jpg",
  "upright row": "Smith_Machine_Upright_Row/0.jpg",
  "upright row barbell": "Upright_Barbell_Row/0.jpg",
  "upright row dumbbell": "Smith_Machine_Upright_Row/0.jpg",
  "walking": "Walking_Treadmill/0.jpg",
  "walking lunge dumbbell": "Barbell_Walking_Lunge/0.jpg",
  "walking lunges": "Barbell_Walking_Lunge/0.jpg",
  "wall calf stretch": "Calf_Stretch_Hands_Against_Wall/0.jpg",
  "weighted pull up": "Weighted_Pull_Ups/0.jpg",
  "weighted sit up": "Weighted_Sit-Ups_-_With_Bands/0.jpg",
  "wide grip pull up": "Wide-Grip_Rear_Pull-Up/0.jpg",
  "wide push up": "Push-Up_Wide/0.jpg",
  "world s greatest stretch": "Worlds_Greatest_Stretch/0.jpg",
  "wrist circles": "Wrist_Circles/0.jpg",
  "wrist curl": "Cable_Wrist_Curl/0.jpg",
  "wrist curl barbell": "Cable_Wrist_Curl/0.jpg",
  "wrist curl dumbbell": "Cable_Wrist_Curl/0.jpg",
  "zercher squat": "Zercher_Squats/0.jpg",
  "zercher squat barbell": "Zercher_Squats/0.jpg",
  "zottman curl": "Zottman_Curl/0.jpg",
  "zottman curl dumbbell": "Zottman_Curl/0.jpg",
};
