export interface ExerciseDef {
  name: string;
  group: string;
  bodyArea?: string; // for PT filter: Knee, Hip, Shoulder, Spine, Ankle, Core, Other
}

export const GYM_EXERCISES: ExerciseDef[] = [
  // Chest
  { name: "Barbell Bench Press", group: "Chest" },
  { name: "Incline Barbell Bench Press", group: "Chest" },
  { name: "Decline Barbell Bench Press", group: "Chest" },
  { name: "Dumbbell Bench Press", group: "Chest" },
  { name: "Incline Dumbbell Press", group: "Chest" },
  { name: "Dumbbell Flyes", group: "Chest" },
  { name: "Cable Crossover", group: "Chest" },
  { name: "Cable Fly", group: "Chest" },
  { name: "Push-Up", group: "Chest" },
  { name: "Dips (Chest)", group: "Chest" },
  { name: "Pec Deck Machine", group: "Chest" },
  // Back
  { name: "Deadlift", group: "Back" },
  { name: "Pull-Up", group: "Back" },
  { name: "Chin-Up", group: "Back" },
  { name: "Lat Pulldown", group: "Back" },
  { name: "Barbell Row", group: "Back" },
  { name: "Dumbbell Row", group: "Back" },
  { name: "Seated Cable Row", group: "Back" },
  { name: "T-Bar Row", group: "Back" },
  { name: "Single-Arm KB Row", group: "Back" },
  { name: "Face Pull", group: "Back" },
  { name: "Hyperextension", group: "Back" },
  // Legs
  { name: "Back Squat", group: "Legs" },
  { name: "Front Squat", group: "Legs" },
  { name: "Romanian Deadlift", group: "Legs" },
  { name: "Leg Press", group: "Legs" },
  { name: "Bulgarian Split Squat", group: "Legs" },
  { name: "Walking Lunges", group: "Legs" },
  { name: "Leg Extension", group: "Legs" },
  { name: "Leg Curl", group: "Legs" },
  { name: "Lying Leg Curl", group: "Legs" },
  { name: "Calf Raise", group: "Legs" },
  { name: "Hip Thrust", group: "Legs" },
  { name: "Goblet Squat", group: "Legs" },
  { name: "Single-Leg RDL", group: "Legs" },
  { name: "Hip Abduction Machine", group: "Legs" },
  { name: "Step-Up (Low Box)", group: "Legs" },
  // Shoulders
  { name: "Overhead Press", group: "Shoulders" },
  { name: "Dumbbell Shoulder Press", group: "Shoulders" },
  { name: "Seated Dumbbell Shoulder Press", group: "Shoulders" },
  { name: "Arnold Press", group: "Shoulders" },
  { name: "Lateral Raise", group: "Shoulders" },
  { name: "Cable Lateral Raise", group: "Shoulders" },
  { name: "Front Raise", group: "Shoulders" },
  { name: "Rear Delt Fly", group: "Shoulders" },
  { name: "Upright Row", group: "Shoulders" },
  { name: "Shrugs", group: "Shoulders" },
  // Arms
  { name: "Barbell Curl", group: "Arms" },
  { name: "Dumbbell Curl", group: "Arms" },
  { name: "Hammer Curl", group: "Arms" },
  { name: "Incline Dumbbell Curl", group: "Arms" },
  { name: "Preacher Curl", group: "Arms" },
  { name: "Concentration Curl", group: "Arms" },
  { name: "Tricep Pushdown", group: "Arms" },
  { name: "Skullcrusher", group: "Arms" },
  { name: "Overhead Tricep Extension", group: "Arms" },
  { name: "Close-Grip Bench Press", group: "Arms" },
  { name: "Dips (Triceps)", group: "Arms" },
  // Core
  { name: "Plank", group: "Core" },
  { name: "Hanging Leg Raise", group: "Core" },
  { name: "Cable Crunch", group: "Core" },
  { name: "Russian Twist", group: "Core" },
  { name: "Ab Wheel Rollout", group: "Core" },
  { name: "Sit-Up", group: "Core" },
  { name: "Mountain Climber", group: "Core" },
  { name: "Pallof Press", group: "Core" },
  { name: "Dead Bug", group: "Core" },
  { name: "Copenhagen Plank", group: "Core" },
  { name: "Cable Woodchop (High to Low)", group: "Core" },
  { name: "Landmine Rotation", group: "Core" },
  // Olympic / Full Body
  { name: "Power Clean", group: "Olympic" },
  { name: "Clean & Jerk", group: "Olympic" },
  { name: "Snatch", group: "Olympic" },
  { name: "Kettlebell Swing", group: "Olympic" },
  { name: "Thruster", group: "Olympic" },
  { name: "Turkish Get-Up", group: "Olympic" },
  { name: "Farmer's Carry", group: "Olympic" },
  // --- JEFIT-sourced expansion (curated, deduped) ---
  // Chest
  { name: "Machine Chest Press", group: "Chest" },
  { name: "Smith Machine Bench Press", group: "Chest" },
  { name: "Incline Cable Fly", group: "Chest" },
  { name: "Low Cable Crossover", group: "Chest" },
  { name: "Svend Press", group: "Chest" },
  { name: "Landmine Press", group: "Chest" },
  { name: "Floor Press", group: "Chest" },
  { name: "Decline Push-Up", group: "Chest" },
  { name: "Diamond Push-Up", group: "Chest" },
  { name: "Archer Push-Up", group: "Chest" },
  { name: "Plyometric Push-Up", group: "Chest" },
  { name: "Resistance Band Chest Press", group: "Chest" },
  { name: "Single-Arm Dumbbell Bench Press", group: "Chest" },
  // Back
  { name: "Wide-Grip Pull-Up", group: "Back" },
  { name: "Neutral-Grip Pull-Up", group: "Back" },
  { name: "Weighted Pull-Up", group: "Back" },
  { name: "Assisted Pull-Up", group: "Back" },
  { name: "Inverted Row", group: "Back" },
  { name: "Pendlay Row", group: "Back" },
  { name: "Meadows Row", group: "Back" },
  { name: "Chest-Supported Row", group: "Back" },
  { name: "Machine Row", group: "Back" },
  { name: "Straight-Arm Pulldown", group: "Back" },
  { name: "Reverse-Grip Lat Pulldown", group: "Back" },
  { name: "Trap Bar Deadlift", group: "Back" },
  { name: "Sumo Deadlift", group: "Back" },
  { name: "Stiff-Leg Deadlift", group: "Back" },
  { name: "Rack Pull", group: "Back" },
  { name: "Good Morning", group: "Back" },
  { name: "Reverse Hyperextension", group: "Back" },
  { name: "Superman", group: "Back" },
  // Legs
  { name: "Hack Squat", group: "Legs" },
  { name: "Smith Machine Squat", group: "Legs" },
  { name: "Box Squat", group: "Legs" },
  { name: "Pause Squat", group: "Legs" },
  { name: "Pistol Squat", group: "Legs" },
  { name: "Reverse Lunge", group: "Legs" },
  { name: "Forward Lunge", group: "Legs" },
  { name: "Lateral Lunge", group: "Legs" },
  { name: "Curtsy Lunge", group: "Legs" },
  { name: "Dumbbell Step-Up", group: "Legs" },
  { name: "Box Jump", group: "Legs" },
  { name: "Sissy Squat", group: "Legs" },
  { name: "Belt Squat", group: "Legs" },
  { name: "Glute Ham Raise", group: "Legs" },
  { name: "Nordic Hamstring Curl", group: "Legs" },
  { name: "Seated Leg Curl", group: "Legs" },
  { name: "Standing Calf Raise", group: "Legs" },
  { name: "Seated Calf Raise", group: "Legs" },
  { name: "Donkey Calf Raise", group: "Legs" },
  { name: "Single-Leg Calf Raise", group: "Legs" },
  { name: "Cable Pull-Through", group: "Legs" },
  { name: "Single-Leg Hip Thrust", group: "Legs" },
  { name: "B-Stance Hip Thrust", group: "Legs" },
  { name: "Cable Kickback", group: "Legs" },
  { name: "Glute Bridge (Barbell)", group: "Legs" },
  { name: "Adductor Machine", group: "Legs" },
  { name: "Cossack Squat", group: "Legs" },
  { name: "Zercher Squat", group: "Legs" },
  // Shoulders
  { name: "Push Press", group: "Shoulders" },
  { name: "Push Jerk", group: "Shoulders" },
  { name: "Behind-the-Neck Press", group: "Shoulders" },
  { name: "Landmine Shoulder Press", group: "Shoulders" },
  { name: "Z Press", group: "Shoulders" },
  { name: "Machine Shoulder Press", group: "Shoulders" },
  { name: "Cable Front Raise", group: "Shoulders" },
  { name: "Plate Front Raise", group: "Shoulders" },
  { name: "Cable Rear Delt Fly", group: "Shoulders" },
  { name: "Reverse Pec Deck", group: "Shoulders" },
  { name: "Bent-Over Lateral Raise", group: "Shoulders" },
  { name: "Leaning Cable Lateral Raise", group: "Shoulders" },
  { name: "Cable Upright Row", group: "Shoulders" },
  { name: "Dumbbell Shrug", group: "Shoulders" },
  { name: "Barbell Shrug", group: "Shoulders" },
  // Arms
  { name: "EZ-Bar Curl", group: "Arms" },
  { name: "Cable Curl", group: "Arms" },
  { name: "Cable Hammer Curl (Rope)", group: "Arms" },
  { name: "Spider Curl", group: "Arms" },
  { name: "Zottman Curl", group: "Arms" },
  { name: "Reverse Curl", group: "Arms" },
  { name: "Drag Curl", group: "Arms" },
  { name: "21s (Bicep)", group: "Arms" },
  { name: "Cable Tricep Kickback", group: "Arms" },
  { name: "Single-Arm Tricep Pushdown", group: "Arms" },
  { name: "Rope Tricep Pushdown", group: "Arms" },
  { name: "Overhead Cable Tricep Extension", group: "Arms" },
  { name: "JM Press", group: "Arms" },
  { name: "Diamond Push-Up (Triceps)", group: "Arms" },
  { name: "Bench Dip", group: "Arms" },
  { name: "Wrist Curl", group: "Arms" },
  { name: "Reverse Wrist Curl", group: "Arms" },
  { name: "Behind-the-Back Wrist Curl", group: "Arms" },
  { name: "Dumbbell Wrist Rotation", group: "Arms" },
  { name: "Plate Pinch Hold", group: "Arms" },
  { name: "Dead Hang", group: "Arms" },
  // Core
  { name: "Side Plank", group: "Core" },
  { name: "Plank with Shoulder Tap", group: "Core" },
  { name: "Hollow Body Hold", group: "Core" },
  { name: "V-Up", group: "Core" },
  { name: "Toes-to-Bar", group: "Core" },
  { name: "Bicycle Crunch", group: "Core" },
  { name: "Reverse Crunch", group: "Core" },
  { name: "Decline Sit-Up", group: "Core" },
  { name: "Weighted Sit-Up", group: "Core" },
  { name: "Dragon Flag", group: "Core" },
  { name: "L-Sit", group: "Core" },
  { name: "Cable Woodchop (Low to High)", group: "Core" },
  { name: "Suitcase Carry", group: "Core" },
  // Olympic / Full body
  { name: "Hang Clean", group: "Olympic" },
  { name: "Hang Snatch", group: "Olympic" },
  { name: "Power Snatch", group: "Olympic" },
  { name: "Clean Pull", group: "Olympic" },
  { name: "Snatch Pull", group: "Olympic" },
  { name: "Overhead Squat", group: "Olympic" },
  { name: "Kettlebell Clean", group: "Olympic" },
  { name: "Kettlebell Snatch", group: "Olympic" },
  { name: "Single-Arm KB Swing", group: "Olympic" },
  { name: "Sled Push", group: "Olympic" },
  { name: "Sled Pull", group: "Olympic" },
  { name: "Battle Ropes", group: "Olympic" },
  { name: "Burpee", group: "Olympic" },
  { name: "Wall Ball", group: "Olympic" },
  { name: "Devil Press", group: "Olympic" },
  { name: "Man Maker", group: "Olympic" },
];

export const PT_EXERCISES: ExerciseDef[] = [
  // Mobility
  { name: "Cat-Cow Stretch", group: "Mobility", bodyArea: "Spine" },
  { name: "Thoracic Rotations", group: "Mobility", bodyArea: "Spine" },
  { name: "Hip 90/90", group: "Mobility", bodyArea: "Hip" },
  { name: "World's Greatest Stretch", group: "Mobility", bodyArea: "Hip" },
  { name: "Ankle Mobility Drill", group: "Mobility", bodyArea: "Ankle" },
  { name: "Shoulder Pass-Through", group: "Mobility", bodyArea: "Shoulder" },
  // Stability
  { name: "Dead Bug", group: "Stability", bodyArea: "Core" },
  { name: "Bird Dog", group: "Stability", bodyArea: "Core" },
  { name: "Side Plank", group: "Stability", bodyArea: "Core" },
  { name: "Pallof Press", group: "Stability", bodyArea: "Core" },
  { name: "Glute Bridge", group: "Stability", bodyArea: "Hip" },
  { name: "Single-Leg Glute Bridge", group: "Stability", bodyArea: "Hip" },
  // Shoulder
  { name: "Band Pull-Apart", group: "Shoulder", bodyArea: "Shoulder" },
  { name: "External Rotation (Band)", group: "Shoulder", bodyArea: "Shoulder" },
  { name: "Internal Rotation (Band)", group: "Shoulder", bodyArea: "Shoulder" },
  { name: "Scapular Wall Slides", group: "Shoulder", bodyArea: "Shoulder" },
  { name: "Y-T-W Raises", group: "Shoulder", bodyArea: "Shoulder" },
  { name: "Prone Snow Angel", group: "Shoulder", bodyArea: "Shoulder" },
  // Knee/Hip
  { name: "Wall Sit", group: "Knee/Hip", bodyArea: "Knee" },
  { name: "Step-Up", group: "Knee/Hip", bodyArea: "Knee" },
  { name: "Terminal Knee Extension", group: "Knee/Hip", bodyArea: "Knee" },
  { name: "Clamshell", group: "Knee/Hip", bodyArea: "Hip" },
  { name: "Monster Walk (Band)", group: "Knee/Hip", bodyArea: "Hip" },
  { name: "Side-Lying Leg Raise", group: "Knee/Hip", bodyArea: "Hip" },
  // Lower Back
  { name: "McKenzie Press-Up", group: "Lower Back", bodyArea: "Spine" },
  { name: "Knee-to-Chest Stretch", group: "Lower Back", bodyArea: "Spine" },
  { name: "Child's Pose", group: "Lower Back", bodyArea: "Spine" },
  { name: "Pelvic Tilt", group: "Lower Back", bodyArea: "Spine" },
  // Foot/Ankle
  { name: "Calf Stretch", group: "Foot/Ankle", bodyArea: "Ankle" },
  { name: "Heel Raises", group: "Foot/Ankle", bodyArea: "Ankle" },
  { name: "Toe Curls", group: "Foot/Ankle", bodyArea: "Ankle" },
  { name: "Single-Leg Balance", group: "Foot/Ankle", bodyArea: "Ankle" },
  // Neck
  { name: "Chin Tuck", group: "Neck", bodyArea: "Spine" },
  { name: "Neck Rotation Stretch", group: "Neck", bodyArea: "Spine" },
  { name: "Upper Trap Stretch", group: "Neck", bodyArea: "Spine" },
  // Fascia
  { name: "Foam Roll - IT Band", group: "Fascia", bodyArea: "Hip" },
  { name: "Foam Roll - Quad", group: "Fascia", bodyArea: "Knee" },
  { name: "Foam Roll - Hip Flexor", group: "Fascia", bodyArea: "Hip" },
  { name: "Foam Roll - Thoracic", group: "Fascia", bodyArea: "Spine" },
  // Stretches
  { name: "Hip Flexor Lunge Stretch", group: "Stretch", bodyArea: "Hip" },
  { name: "Seated Hamstring Stretch", group: "Stretch", bodyArea: "Knee" },
  { name: "Pigeon Pose", group: "Stretch", bodyArea: "Hip" },
  { name: "Standing Quad Stretch", group: "Stretch", bodyArea: "Knee" },
  { name: "Doorway Chest Stretch", group: "Stretch", bodyArea: "Shoulder" },
  { name: "Wall Calf Stretch", group: "Stretch", bodyArea: "Ankle" },
  // Leg Strength (no jumping variants)
  { name: "Squat to Calf Raise", group: "Leg Strength", bodyArea: "Knee" },
  { name: "90-Degree Glute Kickback with Pulses", group: "Leg Strength", bodyArea: "Hip" },
  { name: "Sumo Squat Pulses", group: "Leg Strength", bodyArea: "Hip" },
  { name: "Squat with Knee Drive", group: "Leg Strength", bodyArea: "Knee" },
  { name: "Crab Position Cross-Legged Hip Thrusts", group: "Leg Strength", bodyArea: "Hip" },
  { name: "Superman Leg Abductions", group: "Leg Strength", bodyArea: "Hip" },
  { name: "Modified Side Plank with Leg Raises", group: "Leg Strength", bodyArea: "Core" },
  { name: "Bird-Dog", group: "Leg Strength", bodyArea: "Core" },
  { name: "Squat with 3-Second Isometric Holds", group: "Leg Strength", bodyArea: "Knee" },
  { name: "Single-Leg Squat to Floor Touch", group: "Leg Strength", bodyArea: "Knee" },
  { name: "Lying Side Leg Raises", group: "Leg Strength", bodyArea: "Hip" },
  { name: "Lying Inner Thigh Lifts", group: "Leg Strength", bodyArea: "Hip" },
  { name: "Isometric Squat Hold", group: "Leg Strength", bodyArea: "Knee" },
  { name: "Isometric Lunge Hold", group: "Leg Strength", bodyArea: "Knee" },
  { name: "Lateral Leg Lift to Forward Lunge", group: "Leg Strength", bodyArea: "Hip" },
  { name: "Glute Bridges", group: "Leg Strength", bodyArea: "Hip" },
  { name: "Glute Bridges with 3-Pulse Hold at the Top", group: "Leg Strength", bodyArea: "Hip" },
  { name: "Glute Bridge Pulses", group: "Leg Strength", bodyArea: "Hip" },
  { name: "Side-Step Squats", group: "Leg Strength", bodyArea: "Hip" },
  { name: "High Plank Glute Kickbacks with Knee Drive", group: "Leg Strength", bodyArea: "Hip" },
  { name: "Lateral Lunge with 3-Second Pulses", group: "Leg Strength", bodyArea: "Knee" },
  { name: "Single-Leg Glute Bridge", group: "Leg Strength", bodyArea: "Hip" },
  { name: "Sumo Squat Hold with Heel Raises", group: "Leg Strength", bodyArea: "Hip" },
  { name: "Single-Leg Balance Hold", group: "Leg Strength", bodyArea: "Ankle" },
  // --- JEFIT-sourced PT expansion (curated, deduped) ---
  { name: "Hip Circles", group: "Mobility", bodyArea: "Hip" },
  { name: "Leg Swings (Front-to-Back)", group: "Mobility", bodyArea: "Hip" },
  { name: "Leg Swings (Side-to-Side)", group: "Mobility", bodyArea: "Hip" },
  { name: "Arm Circles", group: "Mobility", bodyArea: "Shoulder" },
  { name: "Wrist Circles", group: "Mobility", bodyArea: "Shoulder" },
  { name: "Spinal Wave", group: "Mobility", bodyArea: "Spine" },
  { name: "Cossack Squat (Mobility)", group: "Mobility", bodyArea: "Hip" },
  { name: "Deep Squat Hold", group: "Mobility", bodyArea: "Hip" },
  { name: "Single-Leg Stance (Eyes Closed)", group: "Stability", bodyArea: "Ankle" },
  { name: "BOSU Balance Hold", group: "Stability", bodyArea: "Ankle" },
  { name: "Tandem Stance", group: "Stability", bodyArea: "Ankle" },
  { name: "Farmer Carry (Single-Arm)", group: "Stability", bodyArea: "Core" },
  { name: "Sleeper Stretch", group: "Shoulder", bodyArea: "Shoulder" },
  { name: "Cross-Body Shoulder Stretch", group: "Shoulder", bodyArea: "Shoulder" },
  { name: "Prone T Raise", group: "Shoulder", bodyArea: "Shoulder" },
  { name: "Prone Y Raise", group: "Shoulder", bodyArea: "Shoulder" },
  { name: "Prone W Raise", group: "Shoulder", bodyArea: "Shoulder" },
  { name: "Wall Angel", group: "Shoulder", bodyArea: "Shoulder" },
  { name: "Short-Arc Quad", group: "Knee/Hip", bodyArea: "Knee" },
  { name: "Long-Arc Quad", group: "Knee/Hip", bodyArea: "Knee" },
  { name: "Straight-Leg Raise", group: "Knee/Hip", bodyArea: "Knee" },
  { name: "Banded Hip Abduction", group: "Knee/Hip", bodyArea: "Hip" },
  { name: "Fire Hydrant", group: "Knee/Hip", bodyArea: "Hip" },
  { name: "Standing Hip Abduction", group: "Knee/Hip", bodyArea: "Hip" },
  { name: "Reverse Clamshell", group: "Knee/Hip", bodyArea: "Hip" },
  { name: "Cobra Stretch", group: "Lower Back", bodyArea: "Spine" },
  { name: "Sphinx Pose", group: "Lower Back", bodyArea: "Spine" },
  { name: "Lumbar Rotation Stretch", group: "Lower Back", bodyArea: "Spine" },
  { name: "Supine Spinal Twist", group: "Lower Back", bodyArea: "Spine" },
  { name: "Towel Scrunches", group: "Foot/Ankle", bodyArea: "Ankle" },
  { name: "Ankle Alphabet", group: "Foot/Ankle", bodyArea: "Ankle" },
  { name: "Banded Ankle Dorsiflexion", group: "Foot/Ankle", bodyArea: "Ankle" },
  { name: "Banded Ankle Inversion/Eversion", group: "Foot/Ankle", bodyArea: "Ankle" },
  { name: "Foam Roll - Calf", group: "Fascia", bodyArea: "Ankle" },
  { name: "Foam Roll - Hamstring", group: "Fascia", bodyArea: "Knee" },
  { name: "Foam Roll - Glute", group: "Fascia", bodyArea: "Hip" },
  { name: "Foam Roll - Lats", group: "Fascia", bodyArea: "Shoulder" },
  { name: "Lacrosse Ball - Foot", group: "Fascia", bodyArea: "Ankle" },
  { name: "Lacrosse Ball - Glute", group: "Fascia", bodyArea: "Hip" },
  { name: "Standing Hamstring Stretch", group: "Stretch", bodyArea: "Knee" },
  { name: "Butterfly Stretch", group: "Stretch", bodyArea: "Hip" },
  { name: "Frog Stretch", group: "Stretch", bodyArea: "Hip" },
  { name: "Couch Stretch", group: "Stretch", bodyArea: "Hip" },
  { name: "Downward Dog", group: "Stretch", bodyArea: "Shoulder" },
  { name: "Cross-Body Glute Stretch", group: "Stretch", bodyArea: "Hip" },
  { name: "Seated Forward Fold", group: "Stretch", bodyArea: "Spine" },
  { name: "Cat Stretch", group: "Stretch", bodyArea: "Spine" },
];

export const PT_BODY_AREAS = ["All", "Knee", "Hip", "Shoulder", "Spine", "Ankle", "Core"] as const;

export const CARDIO_ACTIVITIES = [
  "Running", "Treadmill", "Cycling", "Stationary Bike", "Rowing", "Swimming",
  "Elliptical", "Stair Climber", "Walking", "Hiking", "Jump Rope", "HIIT", "Boxing", "Football",
];
