export interface ExerciseDef {
  name: string;
  group: string;
  bodyArea?: string; // for PT filter: Knee, Hip, Shoulder, Spine, Ankle, Core, Other
}

export const GYM_EXERCISES: ExerciseDef[] = [
  // Chest
  { name: "Barbell Bench Press", group: "Chest" },
  { name: "Incline Barbell Bench Press", group: "Chest" },
  { name: "Decline Barbell Bench Press", group: "Chest" },
  { name: "Dumbbell Bench Press", group: "Chest" },
  { name: "Incline Dumbbell Press", group: "Chest" },
  { name: "Dumbbell Flyes", group: "Chest" },
  { name: "Cable Crossover", group: "Chest" },
  { name: "Cable Fly", group: "Chest" },
  { name: "Push-Up", group: "Chest" },
  { name: "Dips (Chest)", group: "Chest" },
  { name: "Pec Deck Machine", group: "Chest" },
  // Back
  { name: "Deadlift", group: "Back" },
  { name: "Pull-Up", group: "Back" },
  { name: "Chin-Up", group: "Back" },
  { name: "Lat Pulldown", group: "Back" },
  { name: "Barbell Row", group: "Back" },
  { name: "Dumbbell Row", group: "Back" },
  { name: "Seated Cable Row", group: "Back" },
  { name: "T-Bar Row", group: "Back" },
  { name: "Single-Arm KB Row", group: "Back" },
  { name: "Face Pull", group: "Back" },
  { name: "Hyperextension", group: "Back" },
  // Legs
  { name: "Back Squat", group: "Legs" },
  { name: "Front Squat", group: "Legs" },
  { name: "Romanian Deadlift", group: "Legs" },
  { name: "Leg Press", group: "Legs" },
  { name: "Bulgarian Split Squat", group: "Legs" },
  { name: "Walking Lunges", group: "Legs" },
  { name: "Leg Extension", group: "Legs" },
  { name: "Leg Curl", group: "Legs" },
  { name: "Lying Leg Curl", group: "Legs" },
  { name: "Calf Raise", group: "Legs" },
  { name: "Hip Thrust", group: "Legs" },
  { name: "Goblet Squat", group: "Legs" },
  { name: "Single-Leg RDL", group: "Legs" },
  { name: "Hip Abduction Machine", group: "Legs" },
  { name: "Step-Up (Low Box)", group: "Legs" },
  // Shoulders
  { name: "Overhead Press", group: "Shoulders" },
  { name: "Dumbbell Shoulder Press", group: "Shoulders" },
  { name: "Seated Dumbbell Shoulder Press", group: "Shoulders" },
  { name: "Arnold Press", group: "Shoulders" },
  { name: "Lateral Raise", group: "Shoulders" },
  { name: "Cable Lateral Raise", group: "Shoulders" },
  { name: "Front Raise", group: "Shoulders" },
  { name: "Rear Delt Fly", group: "Shoulders" },
  { name: "Upright Row", group: "Shoulders" },
  { name: "Shrugs", group: "Shoulders" },
  // Arms
  { name: "Barbell Curl", group: "Arms" },
  { name: "Dumbbell Curl", group: "Arms" },
  { name: "Hammer Curl", group: "Arms" },
  { name: "Incline Dumbbell Curl", group: "Arms" },
  { name: "Preacher Curl", group: "Arms" },
  { name: "Concentration Curl", group: "Arms" },
  { name: "Tricep Pushdown", group: "Arms" },
  { name: "Skullcrusher", group: "Arms" },
  { name: "Overhead Tricep Extension", group: "Arms" },
  { name: "Close-Grip Bench Press", group: "Arms" },
  { name: "Dips (Triceps)", group: "Arms" },
  // Core
  { name: "Plank", group: "Core" },
  { name: "Hanging Leg Raise", group: "Core" },
  { name: "Cable Crunch", group: "Core" },
  { name: "Russian Twist", group: "Core" },
  { name: "Ab Wheel Rollout", group: "Core" },
  { name: "Sit-Up", group: "Core" },
  { name: "Mountain Climber", group: "Core" },
  { name: "Pallof Press", group: "Core" },
  { name: "Dead Bug", group: "Core" },
  { name: "Copenhagen Plank", group: "Core" },
  { name: "Cable Woodchop (High to Low)", group: "Core" },
  { name: "Landmine Rotation", group: "Core" },
  // Olympic / Full Body
  { name: "Power Clean", group: "Olympic" },
  { name: "Clean & Jerk", group: "Olympic" },
  { name: "Snatch", group: "Olympic" },
  { name: "Kettlebell Swing", group: "Olympic" },
  { name: "Thruster", group: "Olympic" },
  { name: "Turkish Get-Up", group: "Olympic" },
  { name: "Farmer's Carry", group: "Olympic" },
];

export const PT_EXERCISES: ExerciseDef[] = [
  // Mobility
  { name: "Cat-Cow Stretch", group: "Mobility", bodyArea: "Spine" },
  { name: "Thoracic Rotations", group: "Mobility", bodyArea: "Spine" },
  { name: "Hip 90/90", group: "Mobility", bodyArea: "Hip" },
  { name: "World's Greatest Stretch", group: "Mobility", bodyArea: "Hip" },
  { name: "Ankle Mobility Drill", group: "Mobility", bodyArea: "Ankle" },
  { name: "Shoulder Pass-Through", group: "Mobility", bodyArea: "Shoulder" },
  // Stability
  { name: "Dead Bug", group: "Stability", bodyArea: "Core" },
  { name: "Bird Dog", group: "Stability", bodyArea: "Core" },
  { name: "Side Plank", group: "Stability", bodyArea: "Core" },
  { name: "Pallof Press", group: "Stability", bodyArea: "Core" },
  { name: "Glute Bridge", group: "Stability", bodyArea: "Hip" },
  { name: "Single-Leg Glute Bridge", group: "Stability", bodyArea: "Hip" },
  // Shoulder
  { name: "Band Pull-Apart", group: "Shoulder", bodyArea: "Shoulder" },
  { name: "External Rotation (Band)", group: "Shoulder", bodyArea: "Shoulder" },
  { name: "Internal Rotation (Band)", group: "Shoulder", bodyArea: "Shoulder" },
  { name: "Scapular Wall Slides", group: "Shoulder", bodyArea: "Shoulder" },
  { name: "Y-T-W Raises", group: "Shoulder", bodyArea: "Shoulder" },
  { name: "Prone Snow Angel", group: "Shoulder", bodyArea: "Shoulder" },
  // Knee/Hip
  { name: "Wall Sit", group: "Knee/Hip", bodyArea: "Knee" },
  { name: "Step-Up", group: "Knee/Hip", bodyArea: "Knee" },
  { name: "Terminal Knee Extension", group: "Knee/Hip", bodyArea: "Knee" },
  { name: "Clamshell", group: "Knee/Hip", bodyArea: "Hip" },
  { name: "Monster Walk (Band)", group: "Knee/Hip", bodyArea: "Hip" },
  { name: "Side-Lying Leg Raise", group: "Knee/Hip", bodyArea: "Hip" },
  // Lower Back
  { name: "McKenzie Press-Up", group: "Lower Back", bodyArea: "Spine" },
  { name: "Knee-to-Chest Stretch", group: "Lower Back", bodyArea: "Spine" },
  { name: "Child's Pose", group: "Lower Back", bodyArea: "Spine" },
  { name: "Pelvic Tilt", group: "Lower Back", bodyArea: "Spine" },
  // Foot/Ankle
  { name: "Calf Stretch", group: "Foot/Ankle", bodyArea: "Ankle" },
  { name: "Heel Raises", group: "Foot/Ankle", bodyArea: "Ankle" },
  { name: "Toe Curls", group: "Foot/Ankle", bodyArea: "Ankle" },
  { name: "Single-Leg Balance", group: "Foot/Ankle", bodyArea: "Ankle" },
  // Neck
  { name: "Chin Tuck", group: "Neck", bodyArea: "Spine" },
  { name: "Neck Rotation Stretch", group: "Neck", bodyArea: "Spine" },
  { name: "Upper Trap Stretch", group: "Neck", bodyArea: "Spine" },
  // Fascia
  { name: "Foam Roll - IT Band", group: "Fascia", bodyArea: "Hip" },
  { name: "Foam Roll - Quad", group: "Fascia", bodyArea: "Knee" },
  { name: "Foam Roll - Hip Flexor", group: "Fascia", bodyArea: "Hip" },
  { name: "Foam Roll - Thoracic", group: "Fascia", bodyArea: "Spine" },
  // Stretches
  { name: "Hip Flexor Lunge Stretch", group: "Stretch", bodyArea: "Hip" },
  { name: "Seated Hamstring Stretch", group: "Stretch", bodyArea: "Knee" },
  { name: "Pigeon Pose", group: "Stretch", bodyArea: "Hip" },
  { name: "Standing Quad Stretch", group: "Stretch", bodyArea: "Knee" },
  { name: "Doorway Chest Stretch", group: "Stretch", bodyArea: "Shoulder" },
  { name: "Wall Calf Stretch", group: "Stretch", bodyArea: "Ankle" },
  // Leg Strength (28)
  { name: "Squat to Calf Raise", group: "Leg Strength", bodyArea: "Knee" },
  { name: "90-Degree Glute Kickback with Pulses", group: "Leg Strength", bodyArea: "Hip" },
  { name: "Sumo Squat Pulses", group: "Leg Strength", bodyArea: "Hip" },
  { name: "Squat to Calf Raise and Squat Jump Combination", group: "Leg Strength", bodyArea: "Knee" },
  { name: "Squat with Knee Drive", group: "Leg Strength", bodyArea: "Knee" },
  { name: "Crab Position Cross-Legged Hip Thrusts", group: "Leg Strength", bodyArea: "Hip" },
  { name: "Superman Leg Abductions", group: "Leg Strength", bodyArea: "Hip" },
  { name: "Modified Side Plank with Leg Raises", group: "Leg Strength", bodyArea: "Core" },
  { name: "Bird-Dog", group: "Leg Strength", bodyArea: "Core" },
  { name: "Squat Jumps", group: "Leg Strength", bodyArea: "Knee" },
  { name: "Squat with 3-Second Isometric Holds", group: "Leg Strength", bodyArea: "Knee" },
  { name: "Single-Leg Squat to Floor Touch", group: "Leg Strength", bodyArea: "Knee" },
  { name: "Lying Side Leg Raises", group: "Leg Strength", bodyArea: "Hip" },
  { name: "Lying Inner Thigh Lifts", group: "Leg Strength", bodyArea: "Hip" },
  { name: "Isometric Squat Hold", group: "Leg Strength", bodyArea: "Knee" },
  { name: "Isometric Lunge Hold", group: "Leg Strength", bodyArea: "Knee" },
  { name: "Lateral Leg Lift to Forward Lunge", group: "Leg Strength", bodyArea: "Hip" },
  { name: "Glute Bridges", group: "Leg Strength", bodyArea: "Hip" },
  { name: "Glute Bridges with 3-Pulse Hold at the Top", group: "Leg Strength", bodyArea: "Hip" },
  { name: "Glute Bridge Pulses", group: "Leg Strength", bodyArea: "Hip" },
  { name: "Side-Step Squats", group: "Leg Strength", bodyArea: "Hip" },
  { name: "High Plank Glute Kickbacks with Knee Drive", group: "Leg Strength", bodyArea: "Hip" },
  { name: "Lateral Lunge with 3-Second Pulses", group: "Leg Strength", bodyArea: "Knee" },
  { name: "Single-Leg Glute Bridge", group: "Leg Strength", bodyArea: "Hip" },
  { name: "Sumo Squat Hold with Heel Raises", group: "Leg Strength", bodyArea: "Hip" },
  { name: "Single-Leg Balance Hold", group: "Leg Strength", bodyArea: "Ankle" },
  { name: "Kneeling to Squat Jump", group: "Leg Strength", bodyArea: "Knee" },
  { name: "Squat to Squat Jump Combination", group: "Leg Strength", bodyArea: "Knee" },
];

export const PT_BODY_AREAS = ["All", "Knee", "Hip", "Shoulder", "Spine", "Ankle", "Core"] as const;

export const CARDIO_ACTIVITIES = [
  "Running", "Treadmill", "Cycling", "Stationary Bike", "Rowing", "Swimming",
  "Elliptical", "Stair Climber", "Walking", "Hiking", "Jump Rope", "HIIT", "Boxing", "Football",
];
