create table if not exists public.exercises (
  id uuid primary key default gen_random_uuid(),
  name text not null unique,
  muscle_group text not null,
  secondary_muscles text[] not null default '{}',
  equipment text not null,
  exercise_type text not null default 'weight_reps',
  instructions text,
  is_custom boolean not null default false,
  created_by uuid references auth.users(id),
  created_at timestamptz not null default now()
);

alter table public.exercises enable row level security;

drop policy if exists "exercises_read_all" on public.exercises;
create policy "exercises_read_all" on public.exercises for select using (true);

drop policy if exists "exercises_insert_own" on public.exercises;
create policy "exercises_insert_own" on public.exercises for insert with check (auth.uid() = created_by and is_custom = true);

grant select, insert on public.exercises to authenticated;
grant select on public.exercises to anon;
grant all on public.exercises to service_role;

insert into public.exercises (name, muscle_group, secondary_muscles, equipment, exercise_type, instructions) values
('Bench Press (Barbell)', 'Chest', array['Triceps','Shoulders']::text[], 'Barbell', 'weight_reps', 'Lie on a flat bench, grip slightly wider than shoulders. Lower the bar to mid-chest under control, then press up without locking out hard.'),
('Incline Bench Press (Barbell)', 'Chest', array['Shoulders','Triceps']::text[], 'Barbell', 'weight_reps', 'Set the bench to 30-45 degrees. Lower the bar to the upper chest and press back up, keeping elbows about 45 degrees from your torso.'),
('Decline Bench Press (Barbell)', 'Chest', array['Triceps']::text[], 'Barbell', 'weight_reps', 'On a decline bench, lower the bar to the lower chest line and press up, keeping wrists stacked over elbows.'),
('Bench Press (Dumbbell)', 'Chest', array['Triceps','Shoulders']::text[], 'Dumbbell', 'weight_reps', 'Press dumbbells from chest level to full extension above your chest, then lower slowly until elbows reach roughly 90 degrees.'),
('Incline Bench Press (Dumbbell)', 'Chest', array['Shoulders','Triceps']::text[], 'Dumbbell', 'weight_reps', 'On a 30-45 degree incline, press the dumbbells up and slightly together, then lower with control to the sides of the upper chest.'),
('Chest Fly (Dumbbell)', 'Chest', '{}'::text[], 'Dumbbell', 'weight_reps', 'Lying flat with a slight elbow bend, open your arms in a wide arc until you feel a chest stretch, then squeeze back together above your chest.'),
('Incline Chest Fly (Dumbbell)', 'Chest', '{}'::text[], 'Dumbbell', 'weight_reps', 'On an incline bench, arc the dumbbells outward with soft elbows, stretch the upper chest, then bring them back over your face line.'),
('Pullover (Dumbbell)', 'Chest', array['Back']::text[], 'Dumbbell', 'weight_reps', 'Lie across a bench holding one dumbbell over your chest. Lower it behind your head with slightly bent arms, then pull back over the chest.'),
('Chest Press (Machine)', 'Chest', array['Triceps']::text[], 'Strength Machine', 'weight_reps', 'Adjust the seat so handles sit at mid-chest. Press to full extension without locking elbows, then return under control.'),
('Pec Deck Fly (Machine)', 'Chest', '{}'::text[], 'Strength Machine', 'weight_reps', 'With forearms or hands on the pads at chest height, squeeze the pads together in front of you, pause, and return slowly.'),
('Cable Crossover', 'Chest', '{}'::text[], 'Strength Machine', 'weight_reps', 'From high pulleys, pull both handles down and across your body until your hands meet in front of your hips, keeping a slight elbow bend.'),
('Low-to-High Cable Fly', 'Chest', array['Shoulders']::text[], 'Strength Machine', 'weight_reps', 'From low pulleys, sweep the handles upward and inward to shoulder height, targeting the upper chest, then lower with control.'),
('Push-Up', 'Chest', array['Triceps','Abs']::text[], 'Body Weight', 'bodyweight_reps', 'Hands under shoulders, body in a straight line. Lower your chest to just above the floor and press back up without letting hips sag.'),
('Wide Push-Up', 'Chest', array['Shoulders']::text[], 'Body Weight', 'bodyweight_reps', 'Perform a push-up with hands set well outside shoulder width to bias the outer chest.'),
('Decline Push-Up', 'Chest', array['Shoulders','Triceps']::text[], 'Body Weight', 'bodyweight_reps', 'With feet elevated on a bench, lower your chest to the floor and press up, keeping your body rigid.'),
('Chest Dip', 'Chest', array['Triceps']::text[], 'Body Weight', 'weighted_bodyweight', 'On parallel bars, lean your torso forward and lower until your shoulders dip below your elbows, then press up.'),
('Bench Press (Smith Machine)', 'Chest', array['Triceps']::text[], 'Strength Machine', 'weight_reps', 'Use the fixed bar path to press from mid-chest to lockout; set safeties just below chest height.'),
('Floor Press (Kettlebell)', 'Chest', array['Triceps']::text[], 'Kettlebell', 'weight_reps', 'Lying on the floor, press the kettlebell from your chest to full extension; the floor limits range and spares the shoulders.'),
('Chest Press (Band)', 'Chest', array['Triceps']::text[], 'Bands', 'weight_reps', 'Anchor the band behind you at chest height and press both handles forward to full extension.'),
('Incline Cable Fly', 'Chest', '{}'::text[], 'Strength Machine', 'weight_reps', 'On an incline bench between low pulleys, arc the handles up over your chest with soft elbows, then lower until you feel a stretch.'),
('Deadlift (Barbell)', 'Back', array['Glutes','Upper Legs','Forearms']::text[], 'Barbell', 'weight_reps', 'With the bar over mid-foot, hinge and grip just outside your legs. Brace, push the floor away, and stand tall keeping the bar close.'),
('Bent Over Row (Barbell)', 'Back', array['Biceps']::text[], 'Barbell', 'weight_reps', 'Hinge to roughly 45 degrees with a flat back. Row the bar to your lower ribs, squeeze the shoulder blades, and lower under control.'),
('Pendlay Row (Barbell)', 'Back', array['Biceps']::text[], 'Barbell', 'weight_reps', 'From a dead stop on the floor each rep, row the bar explosively to your lower chest with a parallel torso, then return it to the floor.'),
('T-Bar Row', 'Back', array['Biceps']::text[], 'Strength Machine', 'weight_reps', 'Straddle the bar, hinge with a neutral spine, and pull the handles to your chest, driving elbows back and squeezing the mid-back.'),
('One-Arm Row (Dumbbell)', 'Back', array['Biceps']::text[], 'Dumbbell', 'weight_reps', 'With one knee and hand on a bench, row the dumbbell to your hip in an arc, keeping your torso square to the floor.'),
('Chest-Supported Row (Dumbbell)', 'Back', array['Biceps']::text[], 'Dumbbell', 'weight_reps', 'Lie chest-down on an incline bench and row both dumbbells to your hips, pausing at the top squeeze.'),
('Pull-Up', 'Back', array['Biceps']::text[], 'Pullup Bar', 'weighted_bodyweight', 'From a dead hang with an overhand grip, pull your chin over the bar by driving elbows down, then lower fully.'),
('Chin-Up', 'Back', array['Biceps']::text[], 'Pullup Bar', 'weighted_bodyweight', 'With an underhand shoulder-width grip, pull your chin over the bar, emphasizing lats and biceps, then lower with control.'),
('Wide-Grip Pull-Up', 'Back', '{}'::text[], 'Pullup Bar', 'weighted_bodyweight', 'Grip well outside shoulder width and pull your upper chest toward the bar to bias the outer lats.'),
('Assisted Pull-Up (Machine)', 'Back', array['Biceps']::text[], 'Strength Machine', 'assisted_bodyweight', 'Kneel on the assist pad and perform pull-ups; the counterweight offsets part of your body weight.'),
('Lat Pulldown (Cable)', 'Back', array['Biceps']::text[], 'Strength Machine', 'weight_reps', 'Seated with thighs secured, pull the wide bar to your upper chest while keeping your torso tall, then let the arms fully extend.'),
('Close-Grip Lat Pulldown', 'Back', array['Biceps']::text[], 'Strength Machine', 'weight_reps', 'Using a neutral close-grip attachment, pull the handle to your sternum, elbows tracking close to your sides.'),
('Straight-Arm Pulldown (Cable)', 'Back', '{}'::text[], 'Strength Machine', 'weight_reps', 'With nearly straight arms, sweep the bar from eye level down to your thighs, feeling the lats work throughout.'),
('Seated Cable Row', 'Back', array['Biceps']::text[], 'Strength Machine', 'weight_reps', 'Sit tall with knees soft. Pull the handle to your lower abdomen, squeezing shoulder blades together, then extend fully forward.'),
('Seated Row (Machine)', 'Back', array['Biceps']::text[], 'Strength Machine', 'weight_reps', 'With your chest on the pad, row the handles back, driving elbows behind you and pausing at peak contraction.'),
('Face Pull (Cable)', 'Back', array['Shoulders']::text[], 'Strength Machine', 'weight_reps', 'From a high pulley with a rope, pull toward your face while spreading the rope ends apart, finishing with elbows high and back.'),
('Inverted Row', 'Back', array['Biceps']::text[], 'Body Weight', 'bodyweight_reps', 'Hang under a fixed bar with a straight body and pull your chest to the bar, then lower until arms are straight.'),
('Rack Pull (Barbell)', 'Back', array['Glutes','Forearms']::text[], 'Barbell', 'weight_reps', 'Deadlift from knee-height pins: brace, pull the bar up your thighs to lockout, and control it back to the pins.'),
('Good Morning (Barbell)', 'Back', array['Upper Legs','Glutes']::text[], 'Barbell', 'weight_reps', 'With the bar on your upper back, hinge at the hips with soft knees until your torso nears parallel, then stand tall.'),
('Back Extension', 'Back', array['Glutes','Upper Legs']::text[], 'Body Weight', 'bodyweight_reps', 'On a hyperextension bench, hinge down with a neutral spine, then raise your torso until it lines up with your legs.'),
('Superman', 'Back', array['Glutes']::text[], 'Body Weight', 'bodyweight_reps', 'Lying face down, lift your arms, chest, and legs off the floor simultaneously, hold briefly, and lower.'),
('Meadows Row', 'Back', array['Biceps']::text[], 'Barbell', 'weight_reps', 'With a landmine bar perpendicular to you, grip the sleeve end and row it up and back with one arm, elbow flaring slightly.'),
('Band Pull-Apart', 'Back', array['Shoulders']::text[], 'Bands', 'weight_reps', 'Hold a band at shoulder height with straight arms and pull it apart until it touches your chest, squeezing the rear shoulders.'),
('Row (Smith Machine)', 'Back', array['Biceps']::text[], 'Strength Machine', 'weight_reps', 'Hinge over the fixed bar and row it to your lower ribs; the guided path keeps the load stable.'),
('Renegade Row', 'Back', array['Abs']::text[], 'Dumbbell', 'weight_reps', 'In a push-up position on two dumbbells, row one dumbbell to your hip while bracing hard to keep hips level; alternate sides.'),
('Overhead Press (Barbell)', 'Shoulders', array['Triceps']::text[], 'Barbell', 'weight_reps', 'Standing, brace your glutes and abs, then press the bar from your collarbone to lockout overhead, finishing with biceps by your ears.'),
('Seated Shoulder Press (Dumbbell)', 'Shoulders', array['Triceps']::text[], 'Dumbbell', 'weight_reps', 'Seated with back support, press the dumbbells from shoulder height to overhead without clanking them together.'),
('Arnold Press (Dumbbell)', 'Shoulders', array['Triceps']::text[], 'Dumbbell', 'weight_reps', 'Start palms facing you at shoulder height; rotate palms forward as you press overhead, and reverse on the way down.'),
('Shoulder Press (Machine)', 'Shoulders', array['Triceps']::text[], 'Strength Machine', 'weight_reps', 'Adjust the seat so handles start at shoulder level, press to full extension, and lower under control.'),
('Lateral Raise (Dumbbell)', 'Shoulders', '{}'::text[], 'Dumbbell', 'weight_reps', 'With a slight elbow bend, raise the dumbbells out to shoulder height leading with your elbows, then lower slowly.'),
('Lateral Raise (Cable)', 'Shoulders', '{}'::text[], 'Strength Machine', 'weight_reps', 'Standing side-on to a low pulley, raise the handle across and out to shoulder height with a soft elbow.'),
('Front Raise (Dumbbell)', 'Shoulders', '{}'::text[], 'Dumbbell', 'weight_reps', 'Raise the dumbbells straight in front of you to shoulder height with palms down, avoiding body sway.'),
('Front Raise (Plate)', 'Shoulders', '{}'::text[], 'Weight Plate', 'weight_reps', 'Hold a plate at 3 and 9 o''clock and raise it from your thighs to eye level with nearly straight arms.'),
('Rear Delt Fly (Dumbbell)', 'Shoulders', array['Back']::text[], 'Dumbbell', 'weight_reps', 'Hinged forward with a flat back, raise the dumbbells out to your sides with soft elbows, squeezing the rear shoulders.'),
('Reverse Fly (Machine)', 'Shoulders', array['Back']::text[], 'Strength Machine', 'weight_reps', 'Facing the pec deck, sweep the handles back in a wide arc until your arms are in line with your shoulders.'),
('Rear Delt Fly (Cable)', 'Shoulders', array['Back']::text[], 'Strength Machine', 'weight_reps', 'With crossed cables at face height, pull the handles out and back until your arms form a T, then return slowly.'),
('Upright Row (Barbell)', 'Shoulders', array['Back']::text[], 'Barbell', 'weight_reps', 'Pull the bar up your body to chest height, leading with your elbows and keeping the bar close.'),
('Upright Row (Dumbbell)', 'Shoulders', array['Back']::text[], 'Dumbbell', 'weight_reps', 'Pull the dumbbells up along your torso until elbows reach shoulder height, then lower with control.'),
('Shrug (Dumbbell)', 'Shoulders', array['Back']::text[], 'Dumbbell', 'weight_reps', 'Holding dumbbells at your sides, elevate your shoulders straight up toward your ears, pause, and lower — no rolling.'),
('Shrug (Barbell)', 'Shoulders', array['Back']::text[], 'Barbell', 'weight_reps', 'With the bar in front of your thighs, shrug your shoulders straight up, hold the squeeze, and lower slowly.'),
('Push Press (Barbell)', 'Shoulders', array['Triceps','Upper Legs']::text[], 'Barbell', 'weight_reps', 'Dip slightly at the knees and drive the bar overhead in one explosive motion, locking out at the top.'),
('Landmine Press', 'Shoulders', array['Chest','Triceps']::text[], 'Barbell', 'weight_reps', 'With one end of the bar anchored, press the other end up and forward from your shoulder, finishing at an angle.'),
('Shoulder Press (Band)', 'Shoulders', array['Triceps']::text[], 'Bands', 'weight_reps', 'Stand on the band and press the handles from shoulder height to overhead.'),
('Overhead Press (Kettlebell)', 'Shoulders', array['Triceps','Abs']::text[], 'Kettlebell', 'weight_reps', 'With the kettlebell racked at your shoulder, brace and press it overhead until your arm is vertical; lower under control.'),
('Handstand Push-Up', 'Shoulders', array['Triceps']::text[], 'Body Weight', 'bodyweight_reps', 'In a wall-supported handstand, lower your head toward the floor and press back to straight arms.'),
('Bicep Curl (Barbell)', 'Biceps', array['Forearms']::text[], 'Barbell', 'weight_reps', 'With an underhand grip, curl the bar from your thighs to shoulder height keeping elbows pinned to your sides.'),
('Bicep Curl (EZ Bar)', 'Biceps', array['Forearms']::text[], 'EZ Curl Bar', 'weight_reps', 'Curl the angled bar with elbows locked at your sides; the semi-supinated grip is easier on the wrists.'),
('Bicep Curl (Dumbbell)', 'Biceps', array['Forearms']::text[], 'Dumbbell', 'weight_reps', 'Curl both dumbbells with palms up, keeping elbows still, then lower slowly to full extension.'),
('Alternating Bicep Curl (Dumbbell)', 'Biceps', array['Forearms']::text[], 'Dumbbell', 'weight_reps', 'Curl one dumbbell at a time, rotating the palm up as you lift, alternating arms each rep.'),
('Hammer Curl (Dumbbell)', 'Biceps', array['Forearms']::text[], 'Dumbbell', 'weight_reps', 'With palms facing each other throughout, curl the dumbbells to shoulder height and lower with control.'),
('Incline Curl (Dumbbell)', 'Biceps', '{}'::text[], 'Dumbbell', 'weight_reps', 'Seated back on an incline bench with arms hanging behind your torso, curl the dumbbells up for a long biceps stretch.'),
('Concentration Curl (Dumbbell)', 'Biceps', '{}'::text[], 'Dumbbell', 'weight_reps', 'Seated, brace your elbow against your inner thigh and curl the dumbbell to your shoulder with strict form.'),
('Preacher Curl (EZ Bar)', 'Biceps', array['Forearms']::text[], 'EZ Curl Bar', 'weight_reps', 'With upper arms flat on the preacher pad, curl the bar up and lower until arms are almost fully extended.'),
('Bicep Curl (Cable)', 'Biceps', array['Forearms']::text[], 'Strength Machine', 'weight_reps', 'Facing a low pulley, curl the bar to your shoulders with constant cable tension, elbows fixed at your sides.'),
('Rope Hammer Curl (Cable)', 'Biceps', array['Forearms']::text[], 'Strength Machine', 'weight_reps', 'With a rope on the low pulley and neutral grip, curl the ends to shoulder height, keeping elbows still.'),
('Bicep Curl (Machine)', 'Biceps', '{}'::text[], 'Strength Machine', 'weight_reps', 'With arms on the pad and handles gripped, curl through the machine''s arc and lower slowly.'),
('Bicep Curl (Band)', 'Biceps', array['Forearms']::text[], 'Bands', 'weight_reps', 'Stand on the band and curl the handles to your shoulders, resisting on the way down.'),
('Spider Curl (Dumbbell)', 'Biceps', '{}'::text[], 'Dumbbell', 'weight_reps', 'Chest-down on an incline bench with arms hanging vertically, curl the dumbbells up without any swing.'),
('Zottman Curl (Dumbbell)', 'Biceps', array['Forearms']::text[], 'Dumbbell', 'weight_reps', 'Curl palms-up, rotate to palms-down at the top, and lower slowly in the reverse grip.'),
('Close-Grip Bench Press (Barbell)', 'Triceps', array['Chest','Shoulders']::text[], 'Barbell', 'weight_reps', 'Bench press with hands shoulder-width apart, elbows tucked, lowering the bar to your lower chest and pressing to lockout.'),
('Skull Crusher (EZ Bar)', 'Triceps', '{}'::text[], 'EZ Curl Bar', 'weight_reps', 'Lying on a bench, lower the bar toward your forehead by bending only your elbows, then extend back to lockout.'),
('Skull Crusher (Dumbbell)', 'Triceps', '{}'::text[], 'Dumbbell', 'weight_reps', 'Lying down, lower dumbbells beside your head with stationary upper arms, then extend to straight.'),
('Overhead Triceps Extension (Dumbbell)', 'Triceps', '{}'::text[], 'Dumbbell', 'weight_reps', 'Hold one dumbbell overhead with both hands and lower it behind your head, then extend your elbows to press it back up.'),
('Triceps Pushdown (Cable, Rope)', 'Triceps', '{}'::text[], 'Strength Machine', 'weight_reps', 'With a rope on the high pulley, push down and split the rope ends at the bottom, keeping elbows glued to your sides.'),
('Triceps Pushdown (Cable, Bar)', 'Triceps', '{}'::text[], 'Strength Machine', 'weight_reps', 'Push the straight bar from chest height to your thighs, extending fully without leaning over the cable.'),
('Overhead Triceps Extension (Cable)', 'Triceps', '{}'::text[], 'Strength Machine', 'weight_reps', 'Facing away from a low pulley with a rope overhead, extend your elbows forward until your arms are straight.'),
('Triceps Dip', 'Triceps', array['Chest']::text[], 'Body Weight', 'weighted_bodyweight', 'On parallel bars with an upright torso, lower until elbows reach 90 degrees, then press to lockout.'),
('Bench Dip', 'Triceps', array['Shoulders']::text[], 'Bench', 'bodyweight_reps', 'Hands on a bench behind you, legs extended, lower your hips by bending your elbows to 90 degrees and press back up.'),
('Triceps Kickback (Dumbbell)', 'Triceps', '{}'::text[], 'Dumbbell', 'weight_reps', 'Hinged forward with your upper arm parallel to the floor, extend the dumbbell back until your arm is straight.'),
('Triceps Extension (Machine)', 'Triceps', '{}'::text[], 'Strength Machine', 'weight_reps', 'With elbows on the pads, press the handles down and forward through the machine''s arc to full extension.'),
('Diamond Push-Up', 'Triceps', array['Chest']::text[], 'Body Weight', 'bodyweight_reps', 'Push-up with your hands forming a diamond under your chest; keep elbows tracking backward.'),
('Triceps Pushdown (Band)', 'Triceps', '{}'::text[], 'Bands', 'weight_reps', 'Anchor a band overhead and push the ends down to your thighs with pinned elbows.'),
('JM Press (Barbell)', 'Triceps', array['Chest']::text[], 'Barbell', 'weight_reps', 'A hybrid of close-grip bench and skull crusher: lower the bar toward your chin with tucked elbows, then press back up.'),
('Wrist Curl (Barbell)', 'Forearms', '{}'::text[], 'Barbell', 'weight_reps', 'Forearms resting on a bench, palms up, curl the bar using only your wrists through a full range.'),
('Reverse Wrist Curl (Barbell)', 'Forearms', '{}'::text[], 'Barbell', 'weight_reps', 'Forearms on a bench, palms down, raise the bar by extending your wrists, then lower slowly.'),
('Wrist Curl (Dumbbell)', 'Forearms', '{}'::text[], 'Dumbbell', 'weight_reps', 'With your forearm supported and palm up, curl the dumbbell with wrist motion only.'),
('Reverse Curl (Barbell)', 'Forearms', array['Biceps']::text[], 'Barbell', 'weight_reps', 'Curl the bar with an overhand grip, keeping elbows at your sides to load the forearm extensors and brachialis.'),
('Farmer''s Carry (Dumbbell)', 'Forearms', array['Abs','Shoulders']::text[], 'Dumbbell', 'duration', 'Carry heavy dumbbells at your sides with a tall posture, walking for time or distance without letting your grip open.'),
('Plate Pinch Hold', 'Forearms', '{}'::text[], 'Weight Plate', 'duration', 'Pinch one or two plates between your fingers and thumb and hold at your side for time.'),
('Dead Hang', 'Forearms', array['Back']::text[], 'Pullup Bar', 'duration', 'Hang from the bar with straight arms and an engaged grip for as long as possible.'),
('Crunch', 'Abs', '{}'::text[], 'Body Weight', 'bodyweight_reps', 'Lying with knees bent, curl your shoulder blades off the floor, exhale at the top, and lower slowly.'),
('Sit-Up', 'Abs', '{}'::text[], 'Body Weight', 'bodyweight_reps', 'From lying, curl your torso all the way up toward your knees, then roll back down one vertebra at a time.'),
('Plank', 'Abs', array['Shoulders']::text[], 'Body Weight', 'duration', 'On forearms and toes, hold a straight line from head to heels, bracing your abs and glutes.'),
('Side Plank', 'Abs', '{}'::text[], 'Body Weight', 'duration', 'On one forearm with feet stacked, lift your hips to form a straight line and hold; repeat per side.'),
('Hanging Leg Raise', 'Abs', array['Forearms']::text[], 'Pullup Bar', 'bodyweight_reps', 'Hanging from a bar, raise your straight legs to hip height or above without swinging, then lower slowly.'),
('Hanging Knee Raise', 'Abs', '{}'::text[], 'Pullup Bar', 'bodyweight_reps', 'Hanging from a bar, tuck your knees to your chest with a posterior pelvic tilt, then lower under control.'),
('Lying Leg Raise', 'Abs', '{}'::text[], 'Body Weight', 'bodyweight_reps', 'Lying flat with hands under your hips, raise straight legs to vertical and lower without arching your back.'),
('Russian Twist (Weight Plate)', 'Abs', '{}'::text[], 'Weight Plate', 'weight_reps', 'Seated and leaned back with feet up, rotate the plate side to side, tapping it near the floor on each side.'),
('Cable Crunch', 'Abs', '{}'::text[], 'Strength Machine', 'weight_reps', 'Kneeling under a high-pulley rope, crunch your elbows toward your knees by flexing your spine, then return tall.'),
('Ab Crunch (Machine)', 'Abs', '{}'::text[], 'Strength Machine', 'weight_reps', 'Seated in the machine, crunch forward against the resistance and return with control.'),
('Bicycle Crunch', 'Abs', '{}'::text[], 'Body Weight', 'bodyweight_reps', 'Alternate driving each elbow toward the opposite knee while extending the other leg, in a slow controlled cadence.'),
('Mountain Climber', 'Abs', array['Cardio']::text[], 'Body Weight', 'duration', 'From a push-up position, drive your knees alternately toward your chest at pace while keeping hips low.'),
('Rollout (Exercise Ball)', 'Abs', array['Shoulders']::text[], 'Exercise Ball', 'bodyweight_reps', 'Kneeling with forearms on the ball, roll it forward keeping a rigid torso, then pull back with your abs.'),
('Crunch (Exercise Ball)', 'Abs', '{}'::text[], 'Exercise Ball', 'bodyweight_reps', 'With your lower back supported on the ball, crunch your ribs toward your hips and lower into a slight stretch.'),
('Dead Bug', 'Abs', '{}'::text[], 'Body Weight', 'bodyweight_reps', 'On your back with arms and knees up, lower one arm and the opposite leg toward the floor while keeping your back flat; alternate.'),
('Hollow Body Hold', 'Abs', '{}'::text[], 'Body Weight', 'duration', 'Lying on your back, lift shoulders and legs off the floor with your lower back pressed down, and hold the dish shape.'),
('V-Up', 'Abs', '{}'::text[], 'Body Weight', 'bodyweight_reps', 'Simultaneously raise your straight legs and torso to touch your toes at the top, then lower without resting.'),
('Woodchopper (Cable)', 'Abs', array['Shoulders']::text[], 'Strength Machine', 'weight_reps', 'Pull the handle diagonally across your body from high to low with straight-ish arms, rotating through your trunk.'),
('Hip Thrust (Barbell)', 'Glutes', array['Upper Legs']::text[], 'Barbell', 'weight_reps', 'Upper back on a bench with the bar over your hips, drive through your heels until your torso is level, squeezing hard at the top.'),
('Glute Bridge', 'Glutes', array['Upper Legs']::text[], 'Body Weight', 'bodyweight_reps', 'Lying with knees bent, drive your hips up until your body forms a line from knees to shoulders; pause and lower.'),
('Single-Leg Glute Bridge', 'Glutes', array['Upper Legs']::text[], 'Body Weight', 'bodyweight_reps', 'Bridge with one foot planted and the other leg extended, keeping hips level throughout.'),
('Glute Kickback (Cable)', 'Glutes', '{}'::text[], 'Strength Machine', 'weight_reps', 'With an ankle strap on a low pulley, kick your leg straight back and slightly up, squeezing the glute at the top.'),
('Hip Abduction (Machine)', 'Glutes', '{}'::text[], 'Strength Machine', 'weight_reps', 'Seated, push your knees apart against the pads, pause at maximum width, and return slowly.'),
('Kettlebell Swing', 'Glutes', array['Upper Legs','Back','Cardio']::text[], 'Kettlebell', 'weight_reps', 'Hinge and hike the bell between your legs, then snap your hips forward to swing it to chest height — the arms just guide it.'),
('Sumo Deadlift (Barbell)', 'Glutes', array['Upper Legs','Back']::text[], 'Barbell', 'weight_reps', 'With a wide stance and toes out, grip inside your knees, brace, and stand by driving your knees out and hips through.'),
('Frog Pump', 'Glutes', '{}'::text[], 'Body Weight', 'bodyweight_reps', 'Lying with the soles of your feet together and knees out, thrust your hips up and squeeze at the top.'),
('Lateral Band Walk', 'Glutes', '{}'::text[], 'Bands', 'bodyweight_reps', 'With a band around your knees or ankles, take controlled side steps in a quarter squat, keeping tension the whole set.'),
('Donkey Kick', 'Glutes', '{}'::text[], 'Body Weight', 'bodyweight_reps', 'On all fours, kick one bent leg up behind you until your thigh lines up with your torso; squeeze and lower.'),
('Cable Pull-Through', 'Glutes', array['Upper Legs']::text[], 'Strength Machine', 'weight_reps', 'Facing away from a low pulley with the rope between your legs, hinge forward and then snap your hips through to stand tall.'),
('Curtsy Lunge (Dumbbell)', 'Glutes', array['Upper Legs']::text[], 'Dumbbell', 'weight_reps', 'Step one leg behind and across the other into a lunge, then drive back up; alternate sides.'),
('Squat (Barbell)', 'Upper Legs', array['Glutes','Abs']::text[], 'Barbell', 'weight_reps', 'Bar on your upper back, feet shoulder-width. Sit down between your hips until thighs reach parallel, then drive up through mid-foot.'),
('Front Squat (Barbell)', 'Upper Legs', array['Glutes','Abs']::text[], 'Barbell', 'weight_reps', 'With the bar racked on your front delts and elbows high, squat deep keeping your torso as upright as possible.'),
('Goblet Squat (Dumbbell)', 'Upper Legs', array['Glutes']::text[], 'Dumbbell', 'weight_reps', 'Hold a dumbbell vertically at your chest and squat between your knees, keeping your chest tall.'),
('Squat (Smith Machine)', 'Upper Legs', array['Glutes']::text[], 'Strength Machine', 'weight_reps', 'With the bar fixed on rails, set your feet slightly forward and squat to parallel, then drive up.'),
('Hack Squat (Machine)', 'Upper Legs', array['Glutes']::text[], 'Strength Machine', 'weight_reps', 'Back against the pad, lower into a deep knee bend and press through the platform to stand.'),
('Leg Press (Machine)', 'Upper Legs', array['Glutes']::text[], 'Strength Machine', 'weight_reps', 'Feet shoulder-width on the platform, lower the sled until knees near 90 degrees, then press without locking out.'),
('Leg Extension (Machine)', 'Upper Legs', '{}'::text[], 'Strength Machine', 'weight_reps', 'Seated with the pad above your ankles, extend your knees to straight, pause, and lower slowly — no swinging.'),
('Lying Leg Curl (Machine)', 'Upper Legs', '{}'::text[], 'Strength Machine', 'weight_reps', 'Face down with the pad above your heels, curl your legs toward your glutes and lower with control.'),
('Seated Leg Curl (Machine)', 'Upper Legs', '{}'::text[], 'Strength Machine', 'weight_reps', 'Seated with legs extended, curl the pad down and under, squeezing your hamstrings, then return slowly.'),
('Romanian Deadlift (Barbell)', 'Upper Legs', array['Glutes','Back']::text[], 'Barbell', 'weight_reps', 'From standing, push your hips back with soft knees, sliding the bar down your thighs until you feel a hamstring stretch, then stand.'),
('Romanian Deadlift (Dumbbell)', 'Upper Legs', array['Glutes','Back']::text[], 'Dumbbell', 'weight_reps', 'Hinge at the hips with flat back and soft knees, lowering the dumbbells along your legs, then drive hips forward to stand.'),
('Stiff-Leg Deadlift (Barbell)', 'Upper Legs', array['Glutes','Back']::text[], 'Barbell', 'weight_reps', 'With nearly straight knees, hinge until your hamstrings reach a deep stretch, then extend your hips to stand tall.'),
('Walking Lunge (Dumbbell)', 'Upper Legs', array['Glutes']::text[], 'Dumbbell', 'weight_reps', 'Step forward into a lunge until both knees hit 90 degrees, then drive through the front heel into the next step.'),
('Lunge (Barbell)', 'Upper Legs', array['Glutes']::text[], 'Barbell', 'weight_reps', 'With the bar on your back, step forward into a deep lunge and push back to standing; alternate legs.'),
('Reverse Lunge', 'Upper Legs', array['Glutes']::text[], 'Body Weight', 'bodyweight_reps', 'Step backward into a lunge, keeping your front shin vertical, then return to standing.'),
('Bulgarian Split Squat (Dumbbell)', 'Upper Legs', array['Glutes']::text[], 'Dumbbell', 'weight_reps', 'Rear foot elevated on a bench, lower straight down until your front thigh is parallel, then drive up through the front foot.'),
('Step-Up (Dumbbell)', 'Upper Legs', array['Glutes']::text[], 'Dumbbell', 'weight_reps', 'Holding dumbbells, step onto a knee-height bench driving through the top leg, then lower under control.'),
('Bodyweight Squat', 'Upper Legs', array['Glutes']::text[], 'Body Weight', 'bodyweight_reps', 'Squat to at least parallel with arms extended forward for balance, keeping heels down.'),
('Jump Squat', 'Upper Legs', array['Glutes','Cardio']::text[], 'Body Weight', 'bodyweight_reps', 'Squat to parallel and explode upward into a jump, landing softly straight into the next rep.'),
('Wall Sit', 'Upper Legs', '{}'::text[], 'Body Weight', 'duration', 'Slide down a wall until your thighs are parallel and hold the position with shins vertical.'),
('Pistol Squat', 'Upper Legs', array['Glutes','Abs']::text[], 'Body Weight', 'bodyweight_reps', 'Squat on one leg with the other extended forward, descending as low as possible before standing back up.'),
('Nordic Hamstring Curl', 'Upper Legs', '{}'::text[], 'Body Weight', 'bodyweight_reps', 'With ankles anchored, lower your torso forward from your knees as slowly as possible, catching yourself with your hands.'),
('Hip Adduction (Machine)', 'Upper Legs', '{}'::text[], 'Strength Machine', 'weight_reps', 'Seated with legs apart against the pads, squeeze your knees together and return slowly.'),
('Box Squat (Barbell)', 'Upper Legs', array['Glutes']::text[], 'Barbell', 'weight_reps', 'Squat back to a box, pause briefly without relaxing, then drive up explosively.'),
('Zercher Squat (Barbell)', 'Upper Legs', array['Glutes','Abs']::text[], 'Barbell', 'weight_reps', 'Cradle the bar in your elbow creases and squat deep, staying upright against the front load.'),
('Sissy Squat', 'Upper Legs', '{}'::text[], 'Body Weight', 'bodyweight_reps', 'Holding support, rise on your toes and lean your torso back while bending knees forward, then return upright.'),
('Wall Squat (Exercise Ball)', 'Upper Legs', array['Glutes']::text[], 'Exercise Ball', 'bodyweight_reps', 'With the ball between your lower back and a wall, squat until thighs are parallel and roll back up.'),
('Trap Bar Deadlift', 'Upper Legs', array['Glutes','Back']::text[], 'Barbell', 'weight_reps', 'Standing inside the hex bar, grip the handles, brace, and stand tall by driving through the floor.'),
('Standing Calf Raise (Machine)', 'Lower Legs', '{}'::text[], 'Strength Machine', 'weight_reps', 'Shoulders under the pads, balls of feet on the platform, rise as high as possible, pause, and lower into a deep stretch.'),
('Seated Calf Raise (Machine)', 'Lower Legs', '{}'::text[], 'Strength Machine', 'weight_reps', 'With the pad on your knees, raise your heels to full height and lower slowly to a stretch to hit the soleus.'),
('Calf Raise (Barbell)', 'Lower Legs', '{}'::text[], 'Barbell', 'weight_reps', 'With the bar on your back and toes on a small ledge, perform slow full-range heel raises.'),
('Calf Raise (Dumbbell)', 'Lower Legs', '{}'::text[], 'Dumbbell', 'weight_reps', 'Holding dumbbells at your sides, rise onto the balls of your feet, pause, and lower with control.'),
('Single-Leg Calf Raise', 'Lower Legs', '{}'::text[], 'Body Weight', 'bodyweight_reps', 'On one foot with toes on a step, perform full-range calf raises, using a wall for balance only.'),
('Calf Press (Leg Press Machine)', 'Lower Legs', '{}'::text[], 'Strength Machine', 'weight_reps', 'On the leg press with only your toes on the platform, press through the balls of your feet without moving your knees.'),
('Donkey Calf Raise', 'Lower Legs', '{}'::text[], 'Body Weight', 'bodyweight_reps', 'Hinged forward with your hands supported, drive up onto your toes for a stretched-position calf raise.'),
('Tibialis Raise', 'Lower Legs', '{}'::text[], 'Body Weight', 'bodyweight_reps', 'Leaning back against a wall with straight legs, lift your toes toward your shins as high as possible.'),
('Running (Outdoor)', 'Cardio', array['Upper Legs','Lower Legs']::text[], 'Body Weight', 'distance_duration', 'Run at a steady conversational pace or in intervals; log distance and duration.'),
('Treadmill Run', 'Cardio', array['Upper Legs']::text[], 'Cardio Machine', 'distance_duration', 'Run on the treadmill at your target pace or incline; log distance and duration.'),
('Walking', 'Cardio', array['Upper Legs']::text[], 'Body Weight', 'distance_duration', 'Brisk continuous walking, outdoors or on a treadmill; log distance and duration.'),
('Cycling (Stationary Bike)', 'Cardio', array['Upper Legs']::text[], 'Cardio Machine', 'distance_duration', 'Pedal at a steady cadence or in intervals with moderate resistance; log distance and duration.'),
('Rowing Machine', 'Cardio', array['Back','Upper Legs']::text[], 'Cardio Machine', 'distance_duration', 'Drive with legs, then swing your torso and pull the handle to your ribs; reverse the sequence on the return.'),
('Elliptical Trainer', 'Cardio', array['Upper Legs']::text[], 'Cardio Machine', 'distance_duration', 'Maintain a smooth stride using both handles and pedals; log duration and distance.'),
('Stair Climber', 'Cardio', array['Glutes','Upper Legs']::text[], 'Cardio Machine', 'distance_duration', 'Climb at a steady pace with a tall posture, using the rails only for balance.'),
('Jump Rope', 'Cardio', array['Lower Legs']::text[], 'Body Weight', 'duration', 'Skip with small, quick bounces on the balls of your feet, wrists doing the turning.'),
('Burpee', 'Cardio', array['Chest','Upper Legs']::text[], 'Body Weight', 'bodyweight_reps', 'Squat, kick back to a push-up, return your feet under you, and jump up — one fluid rep.'),
('Jumping Jack', 'Cardio', '{}'::text[], 'Body Weight', 'bodyweight_reps', 'Jump your feet out while raising your arms overhead, then return; keep a springy rhythm.'),
('High Knees', 'Cardio', array['Abs']::text[], 'Body Weight', 'duration', 'Run in place driving your knees to hip height at a fast cadence.'),
('Assault Bike', 'Cardio', array['Upper Legs','Shoulders']::text[], 'Cardio Machine', 'distance_duration', 'Drive the pedals and handles together at high effort, in intervals or steady state.')
on conflict (name) do nothing;